### ISSUE TITLE
Test P53

### ISSUE THREAD

**Issue by KwatME** [KwatME/gsea#10]
@ACastanza

**Comment by KwatME** [comment]
I don't know what edb/ is but assuming that GSEA saved its input files there, these ones GSEA saved and the ones in the testing folder are different. What is happening here?

![Screen Shot 2021-07-23 at 11 57 48](https://user-images.githubusercontent.com/7741548/126822615-38ff2082-1517-4c15-8667-92914304106f.png)
![Screen Shot 2021-07-23 at 11 58 06](https://user-images.githubusercontent.com/7741548/126822621-bca03441-6e52-4bd9-9f35-eafa4cb0227e.png)

**Comment by ACastanza** [comment]
edb is where GSEA stores the results of it's internal operations - ranking the genes, and filtering the gene sets on the size thresholds, etc. Any differences in the ranked lists would have to come from differences in the S2N implementation

**Comment by KwatME** [comment]
Thanks for the pointer. I think this is messing up the signal to noise ranking function.

**Comment by KwatME** [comment]
Here is the notebook for testing: https://github.com/KwatME/gsea/blob/master/nb/test_p53.ipynb

Looks like the S2N is a bit off in amplitude and opposite in sign.

Please run this notebook and let me know your interpretation.

**Comment by ACastanza** [comment]
Oh! I can explain the opposite in sign thing. In Desktop GSEA you have to pick the phenotype direction and I'd picked MUT_versus_WT, but in the CLS WT is listed first, which would flip it. Here's a rerun with the same seed with the direction corrected:
[P53_Biocarta_Direction_Fix.Gsea.1627065897323.zip](https://github.com/KwatME/gsea/files/6870638/P53_Biocarta_Direction_Fix.Gsea.1627065897323.zip)

**Comment by ACastanza** [comment]
Also, I'm not able to run the notebook, I haven't been able to get the "kwat.py" file to install locally, which is probably an issue with my conda environment (since I was able to get everything to work in docker).

**Comment by KwatME** [comment]
Oh may be you need to get git-lfs.
See README.md here 
https://github.com/KwatME/kwat.py

This library carries some large files and git-lfs is needed to get them.

**Comment by KwatME** [comment]
No matter how I do the S2N, the values are a bit off. Do you have the exact implementation of the old S2N?

**Comment by ACastanza** [comment]
I know what it looks like in the R code: https://github.com/GSEA-MSigDB/GSEA_R/blob/master/R/GSEA.GeneRanking.R (it enables the "GeneCluster" sigma.correction).
But I don't know anything about the Java code, that'd be a question for David. It's somewhere in the repo: https://github.com/GSEA-MSigDB/gsea-desktop/

From: Kwat Medetgul-Ernar ***@***.***>
Date: Friday, July 23, 2021 at 3:53 PM
To: KwatME/gsea ***@***.***>
Cc: Anthony S. Castanza ***@***.***>, Mention ***@***.***>
Subject: Re: [KwatME/gsea] Test P53 (#10)

No matter how I do the S2N, the values are a bit off. Do you have the exact implementation of the old S2N?

**Comment by KwatME** [comment]
![Screen Shot 2021-07-23 at 17 23 45](https://user-images.githubusercontent.com/7741548/126849872-3418850f-ea03-4e37-a89b-4adaee604d37.png)

Just a bit off. I'll keep looking into this.

**Comment by KwatME** [comment]
@davideby

Can you point me to S2N in Java?

Thanks!

**Comment by ACastanza** [comment]
That's close enough that I'd suspect a sigfigs/rounding issue

**Comment by KwatME** [comment]
Let me clean up what I have and push it.

**Comment by KwatME** [comment]
![Uploading Screen Shot 2021-07-23 at 17.32.17.png…]()
