### ISSUE TITLE
TypeError: run_gsea() got an unexpected keyword argument 'se'

### ISSUE THREAD

**Issue by ACastanza** [KwatME/gsea#15]
I changed the se parameter in my code from se to ra as specified in the updated documentation, but keep getting this error

Full message:
```

Traceback (most recent call last):
  File "/opt/gpbeta_2/gp_home/taskLib/GSEA2.1.2063/run.gsea2.py", line 74, in <module>
    main()
  File "/opt/gpbeta_2/gp_home/taskLib/GSEA2.1.2063/run.gsea2.py", line 54, in main
    nu_se_st = run_gsea(
TypeError: run_gsea() got an unexpected keyword argument 'se'

```

**Comment by KwatME** [comment]
Are you sure se is not being accidentally passed? Did you update the gsea.py? It is expected that unexpected keyword argument error is thrown is se is passed. Since this error occurs when calling run_gsea, there is not much I can do by looking at run_gsea, other than confirming that se is not an argument or keyword argument:
![Screen Shot 2021-07-26 at 15 15 24](https://user-images.githubusercontent.com/7741548/127060218-5260cf1a-b015-460b-9b5a-592c8229d7f3.png)

**Comment by ACastanza** [comment]
https://github.com/ACastanza/GSEA2/blob/main/src/run.gsea2.py
You can see its running the function that starts on line 54 which does not contain an "se" parameter.
And the container is updated since it would be erroring the other direction if it wasn't (expecting se but getting ra).
Is it maybe calling down to some other part of the code and passing an "se" parameter?

**Comment by KwatME** [comment]
That's so weird. I doubled checked and there is no se. And your function looks good too. Strange.

**Comment by ACastanza** [comment]
I removed the commented code block that contains the old function and am running another test. It shouldn't make a difference, but maybe there was some sort of weird caching going on. Job is still running

**Comment by KwatME** [comment]
I see. Then it is seeing the older version.
Can you build once more? (getting the latest kwat.py, gsea, Kwat.jl).
I just tested ranking functions other than signal-to-noise, and all worked ok. So it is good time to get the latest of all.
Thanks.

**Comment by ACastanza** [comment]
It still hasn't errored so I think removing that code block fixed it, probably by forcing a rebuild.
One thing that I'd suggest is readding the ic ranking metric so we can continue doing old method vs new method comparisons

**Comment by KwatME** [comment]
Reading it from a file? Or you mean to add "information coefficient" as another ranking method?

**Comment by ACastanza** [comment]
re-adding. At some point you removed the "ic" ranking metric, which I assumed was used for the new method
