### ISSUE TITLE
Series/Sequence Shuffle Behavior Warning

### ISSUE THREAD

**Issue by ACastanza** [KwatME/gsea#17]
```
run_gsea.py:83: UserWarning:

you are shuffling a 'Series' object which is not a subclass of 'Sequence'; `shuffle` is not guaranteed to behave correctly. E.g., non-numpy array/tensor objects with view semantics may contain duplicates after shuffling.

```

Behavior of permutation shuffling should be validated (if not already) and if confirmed to behave correctly this warning should be disabled/hidden. Ideal solution would be to convert to the proper/expected data structure (Sequence).

**Comment by KwatME** [comment]
![Screen Shot 2021-07-26 at 20 37 29](https://user-images.githubusercontent.com/7741548/127086259-fe4b08b8-816a-407c-9c1e-26b2e2fb1698.png)

**Comment by ACastanza** [comment]
Ok, so you changed the data type to an array from what it was previously. I'd note that now the previous procedure where we provided an index of sample names as a part of the phenotype object now no longer works as the numpy array class does not support an index

`AttributeError: 'numpy.ndarray' object has no attribute 'index'`

This means if there was any plan to use that information it will now no longer be attached to the object.

I'll give it a try with this data type, perhaps that is also the root cause of the permutation speed issue.

**Comment by KwatME** [comment]
Sounds good.

If it is better to use Series, which can take the sample labels, please let me know. We can do that.

The reason we went with array is because we are asking the users often input labels like "1 1 1 0 0 ...", having the sample order in mind. I'm indifferent to Series or array. Just let me know what works for you.
