### ISSUE TITLE
Permutation Calculation Speed

### ISSUE THREAD

**Issue by ACastanza** [KwatME/gsea#18]
Job timed out with 1000 permutations on 1 CPU with 2 hour time limit.
Equivalent job with identical resource allocation completes in <10 minutes using java core GSEA.

Stdout shows completion of only two permutations in two hours
```
Selected 615 sets (5 <= size <= 500).
Permuting labels to compute p-values...
  1/1000
  2/1000
```

**Comment by KwatME** [comment]
This is slow. Can you try passing in numpy array as the input and let me know the speed? How many samples are you using?

**Comment by KwatME** [comment]
Can you send me the data and running configuration you used for this test?

**Comment by KwatME** [comment]
I tired to run 9 samples with 5K< gene sets and 10 permutations took less than 10 seconds.

![Screen Shot 2021-07-26 at 20 59 34](https://user-images.githubusercontent.com/7741548/127088384-89bf4bd8-8218-41bf-bdbb-280fe7ddff4a.png)

**Comment by ACastanza** [comment]
I switched to using a numpy array for the phenotype labels and this did not improve the calculation speed.
I'm running this sarcopenia dataset with signal to noise ranking, the ks statistic, 1000 label permutations, and the Wikipathways gene sets.
[Sarcopenia_Test_Data.zip](https://github.com/KwatME/gsea/files/6887083/Sarcopenia_Test_Data.zip)
The test job with the numpy array has been running over night and has still not completed.

**Comment by KwatME** [comment]
Let me take a look.

**Comment by KwatME** [comment]
I made https://github.com/KwatME/gsea/blob/master/nb/test_sarcopenia.ipynb. Take a look. run_gsea with 10 permutations took about 30 seconds. In your environment, try running this notebook. I think something else may be stuck in your case? What could it be?

**Comment by KwatME** [comment]
In your docker environment, you can start the notebook and navigate to this new notebook. It should run.

**Comment by ACastanza** [comment]
I don't think it has the stuff installed in it to actually run notebooks, at least I didn't install it explicitly, but you can take a look.
The container is available from here: https://hub.docker.com/r/acastanza/gsea2/tags
I only installed what is in the dockerfile you've seen. My assumption would be that you have something installed that is accelerating the computation but that isn't explicitly required (and isn't listed as a dependency).

**Comment by KwatME** [comment]
Installation looks good. The docker is getting everything, including things to run notebook. I'm not sure what's going on.

**Comment by KwatME** [comment]
You can add "IJulia" as one of the Juila packages being installed to make sure that you can run notebook (I'll add this gsea's README now). If your notebook runs fine but the script is slow, then there is something strange in the scrip.

**Comment by KwatME** [comment]
@alex-wenzel and @davideby ,

Can you guys run https://github.com/KwatME/gsea/blob/master/nb/test_sarcopenia.ipynb and let us know how it goes?

**Comment by ACastanza** [comment]
You can see the script, it is literally just running the run_gsea command

**Comment by KwatME** [comment]
I see that. But the outcome is different. So something has to be different. Maybe try matching all the arguments to that of notebook?

**Comment by ACastanza** [comment]
I set up the parameters to replicate desktop GSEA as closely as I could. If it can't replicate desktop GSEA that is an issue.
I ran my script, in the container, passing the GCT, GMT, and CLS, along with "signal_to_noise" and "ks", leaving everything else as the script's defaults (set up to mimic Desktop GSEA).
If you want to try tweaking parameters to see what the issue might be, I've exposed all the options to the script's command line parser.

**Comment by KwatME** [comment]
I looked at https://github.com/ACastanza/GSEA2/blob/main/src/run.gsea2.py and copied all inputs into the notebook call.
I was able to run it and it took 20 seconds to finish up to this point. It will likely finish 1000 in few minutes.

![Screen Shot 2021-07-27 at 12 02 21](https://user-images.githubusercontent.com/7741548/127205057-b3561d2c-c289-47da-8c65-114b74534669.png)

**Comment by ACastanza** [comment]
Well then I'd ask you try it in the docker container, because I created the container to your defined spec. If it isn't running properly than there is something wrong.

**Comment by KwatME** [comment]
I can try this later. Let's see if @alex-wenzel and @davideby encounter the same problem. I will keep this open until you are able to reproduce the same speed.

**Comment by alex-wenzel** [comment]
I am traveling this week so I can't promise a timely response, but I will try to run the Docker container locally and replicate @ACastanza's analysis.

**Comment by ACastanza** [comment]
The command I'm using to run the docker container locally:
` docker run --mount type=bind,src="/Users/acastanza/Sarcopenia_Test_Data",dst="/data" acastanza/gsea2 "python" "/src/run.gsea2.py" "-g" "/data/GSE111016_allSamplesCounts_htseqcov1_sss_forGEO.Sarcopenia.vs.Normal_counts_collapsed_to_symbols.gct.gct" "-c" "/data/Sarcopenia_bianry.cls" "-m" "/data/c2.cp.wikipathways.v7.4.symbols.gmt" "-r" "signal_to_noise" "-e" "ks"`
 
 This also appears to be running extremely slowly

**Comment by ACastanza** [comment]
I found a reference to something similar here: http://julia-programming-language.2336112.n4.nabble.com/Very-poor-performance-on-Linux-td25592.html

**Comment by KwatME** [comment]
macOS

**Comment by ACastanza** [comment]
Okay, that thread seems to indicate that it is an issue with using the precompiled linux binary. So I'm going to try switching back to their official julia image and change how I install python 3.7 in it, and if that still doesn't work, start from a base linux image and compile everything from scratch.

**Comment by ACastanza** [comment]
Confirmed, this is an issue with the precompiled julia binary for linux. Switching to the official julia docker image resolved the issue. However, even installing python from pip causes the "UnsupportedPythonError" requiring the script to launch with the "python-jl" workaround.
Investigating additional possible resolutions, but this seems to work for now.

**Comment by ACastanza** [comment]
Well, I thought it was working, and it runs the first 10 permutations reasonably quickly and then it just.... seems to get stuck.
Have you tried running more than 10 permutations?

**Comment by KwatME** [comment]
More than 10 permutations works fine. Memory grows as expected (not much).

![Screen Shot 2021-07-27 at 19 54 28](https://user-images.githubusercontent.com/7741548/127251305-98e62f7b-0d56-4c71-97aa-51994d9a9aab.png)

![Screen Shot 2021-07-27 at 19 55 29](https://user-images.githubusercontent.com/7741548/127251321-fe5d3727-c5cd-4c29-8f4a-3575f27d4bf8.png)

At this point, the problem is not the speed anymore. It is probably something to do with the docker, build, and/or the interface between these components.
