### ISSUE TITLE
Suggested code for reading GMTs fails with most collections

### ISSUE THREAD

**Issue by ACastanza** [KwatME/gsea#4]
gm = pd.read_csv(
    "data/h.all.v7.1.symbols.gmt", sep="\t", header=None, index_col=0
).drop(1, axis=1)

works with the hallmarks, but fails with (for example) Reactome with:

`Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/anaconda3/lib/python3.8/site-packages/pandas/io/parsers.py", line 610, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/usr/local/anaconda3/lib/python3.8/site-packages/pandas/io/parsers.py", line 468, in _read
    return parser.read(nrows)
  File "/usr/local/anaconda3/lib/python3.8/site-packages/pandas/io/parsers.py", line 1057, in read
    index, columns, col_dict = self._engine.read(nrows)
  File "/usr/local/anaconda3/lib/python3.8/site-packages/pandas/io/parsers.py", line 2036, in read
    data = self._reader.read(nrows)
  File "pandas/_libs/parsers.pyx", line 756, in pandas._libs.parsers.TextReader.read
  File "pandas/_libs/parsers.pyx", line 771, in pandas._libs.parsers.TextReader._read_low_memory
  File "pandas/_libs/parsers.pyx", line 827, in pandas._libs.parsers.TextReader._read_rows
  File "pandas/_libs/parsers.pyx", line 814, in pandas._libs.parsers.TextReader._tokenize_rows
  File "pandas/_libs/parsers.pyx", line 1951, in pandas._libs.parsers.raise_parser_error
pandas.errors.ParserError: Error tokenizing data. C error: Expected 13 fields in line 2, saw 181`

**Comment by KwatME** [comment]
Did you change the path correctly?

Can you send me the .gmt where this fails?

**Comment by ACastanza** [comment]
Yes I changed the path correctly. I tried it with hallmarks and it works, but Reactome fails: https://www.gsea-msigdb.org/gsea/msigdb/download_file.jsp?filePath=/msigdb/release/7.4/c2.cp.reactome.v7.4.symbols.gmt

As does PID, they're all available from here: https://www.gsea-msigdb.org/gsea/downloads.jsp

**Comment by KwatME** [comment]
This is because I tried to mimic how people read .gmt as DataFrame, which is a bad practice because the number of entries per row (genes per set) is different.

A better way to read .gmt is as a dictionary, key is set and value is a list of genes.

I updated the notebook to use the ideal way of reading .gmt.

Further thing to think about: gm can be DataFrame or dict now, but we may want to accept only dictionary to avoid this error with future users.

What do you think?

Finally, the fix is pushed.

**Comment by KwatME** [comment]
I should not have closed this issue. I'm reopening it. When this is resolved, just close it.

**Comment by KwatME** [comment]
@alex-wenzel , reading .gmt is probably better done as dict. What do you think?

**Comment by ACastanza** [comment]
Edwin uses this function in his python GSEA to read GMTs:
```

def read_gmt(path):
    """
    Returns two dictionaries, one mapping from gene set to genes
    and one mapping from gene to gene sets.

        path (str): Local filepath for a .gmt file

        returns ({str: [str]}, {str: [str]}): Mappings as described above
    """
    gene2gs = {}
    gs2gene = {}
    for line in open(path).readlines():
        tokens = line.strip('\n').split('\t')
        gs = tokens[0]
        genes = tokens[2:]
        for g in genes:
            try: ## populate gene to gene set mapping
                gene2gs[g].append(gs)
            except KeyError:
                gene2gs[g] = [gs]
            try: ## populate gene set to gene mapping
                gs2gene[gs].append(g)
            except KeyError:
                gs2gene[gs] = [g]
    return gene2gs, gs2gene


```

I might suggest supporting data as formatted from this function

**Comment by KwatME** [comment]
This works.
Then let's cement the use case where .gmt is read as dictionary: key = gene set and value = list of genes.
