### ISSUE TITLE
Incomplete results

### ISSUE THREAD

**Issue by ACastanza** [KwatME/gsea#7]
No P or Q values are returned, no enrichment plots are produced, no output other than the (incomplete, missing p/q values) statistics.tsv is written to the output directory.

Are there functions to extract these additional pieces of information?
What exactly is implemented in this version of GSEA?

**Comment by ACastanza** [comment]
Additionally, three of the gene sets in the Reactome database, returned blank enrichment scores as well
[statistics.txt](https://github.com/KwatME/gsea/files/6865243/statistics.txt)
(renamed extension from tsv to txt because of github fiel restrictions)

**Comment by KwatME** [comment]
Results should be complete now. Let's check the accuracy comparing with the old software.

**Comment by KwatME** [comment]
Push took some time.
Updated README.md.
Note the change in some arguments.
Thanks for being patient. Let's get this working!

**Comment by ACastanza** [comment]
Are you actually trying to drive me insane? You keep changing completely unrelated things.
Now, for example, a bunch of the ranking methods that were previously there are gone (or at least not documented), and now there is no normalization parameter at all - which is not what I asked for, I just wanted a "none" option for the existing parameter.

Also, the trailing underscore for the "se_el_" parameter, is this actually correct? If so, please trim it, it's unnecessary (also, the parameter didn't really need to change in the first place).

Finally, you've changed the order of some of the parameters. I agree with moving up the permutation type parameter, but, assuming that the order you've given in the readme is important, please move the number of permutations up with it as well.

**Comment by KwatME** [comment]
Let's first make sure that the p53 example works. Even if we have the rest of the things perfect, if it does not work, then we end up wasting time.

After having looked at the GSEA2, I assumed that GSEA2 repo would be the interface for the public? If so, then that is the level where we should perfect the variables. If this is not the case, then I need to update the parameters.

"_" is not a typo - it signifies iterable-like.

Also, this is the hot stage of the development and things often change. Especially right now our metric is to get the results correct. Then we can decide which function/file/module is the interface for what.

I'm happy to have the GSEA2 the interface as well. Whatever is easy for you. But now, I just have to test with the p53 data set (let me know which C2 to use for that).

**Comment by ACastanza** [comment]
GSEA2 is just the wrapper for interacting with the Docker container and running this on GenePattern, it wasn't intended to be distributed as part of this code for general user interaction - it can become that if we want to go that direction, but my expectation was that the parameters in your function would be generally user comprehensible such that someone could run the function directly and for the most part, understand what they do.

**Comment by KwatME** [comment]
Got it. Let's make this as easy for you as possible when the time comes. I just want to make the core run correctly for you all.

**Comment by KwatME** [comment]
Last big thing missing from the functionality is to save static figures. See #11
