### ISSUE TITLE
si+ks not producing equivalent results to desktop GSEA

### ISSUE THREAD

**Issue by ACastanza** [KwatME/gsea#8]
I ran the same dataset with the same gene sets in desktop GSEA and in the new GSEA with si and ks with we=1, the results would be expected to be comparable. They were not even remotely similar. I would suspect that this has to do with the parameter:
`no="-0-",  # Normalization method; "-0-", "0-1", "1234", "log"`
I'd I'm interpreting this symbology correctly these are zero-centered, zero to one, ????, and log transform (base?)?
Is there an "off" option? I assume this is a normalization imposed on the expression data? In that case the equivalent behavior to Desktop GSEA would be: "none" 

Desktop GSEA does have a "normalization mode" parameter but that has to do with normalizing the enrichment scores, not the data

Edit: I should note, not just "not equivalent" but also substantially worse in terms of enrichment of expected gene sets that explain known biology.

**Comment by KwatME** [comment]
I see. Let me add no-normalization option. Does the desktop app have any way to normalize the input data?
Also, this test is great. Let's do this again when I add this option.

**Comment by ACastanza** [comment]
The desktop GSEA app does not normalize the input data at all.

**Comment by KwatME** [comment]
Got it.

**Comment by KwatME** [comment]
I fixed the bugs. Can you send me the input files and parameters given for this run? I want to run it and make sure the results are what it should be.

**Comment by ACastanza** [comment]
You can test with the P53 example dataset from the GSEA website. I recommend using the P53_hgu95av2.gct version and first running it through CollapseDataset (there's a module on GenePattern) using the Human_AFFY_HG_U95_MSigDB.v7.4.chip over the old pre-converted one.

https://www.gsea-msigdb.org/gsea/datasets.jsp

**Comment by KwatME** [comment]
Can you send me the file that gets fed into GSEA (after all these modifications you mentioned is done)?

**Comment by KwatME** [comment]
![Screen Shot 2021-07-23 at 11 11 18](https://user-images.githubusercontent.com/7741548/126817571-15a1ff8c-258f-49df-9781-806e21bef095.png)

Can I just use the collapsed gct and the cls directly? Then compare with the C2 results? And I use only C2 for this test right? Which version of C2 do I use?

**Comment by ACastanza** [comment]
Use this. I've included the pre-collapsed data, a CLS, the GMT to use, as well as the results from running it in GSEA with default settings. [Test_Data_with_Expected_Result.zip](https://github.com/KwatME/gsea/files/6870271/Test_Data_with_Expected_Result.zip)

**Comment by KwatME** [comment]
Thank you. This makes it so much easier. You made the docker work. Now it's my turn to make the results correct. Then you can reproduce it in your docker. And let's update things (names, normalization, etc) after?

**Comment by ACastanza** [comment]
I think the normalization parameters are still important. We need a "none" option for running in legacy GSEA mode, but I don't know if the new algorithm mode expects them to be set a certain way. Also ssGSEA mode will need them exposed.

**Comment by KwatME** [comment]
Got it. I'll put it back. I removed it temporarily to remove it from the thinking process as we test. Working on p53 now.

**Comment by ACastanza** [comment]
Removing things temporarily just makes more work since we all have to make extra modifications to our scripts not pass invalid parameters, and then we have to go put them back afterward. And also unnecessary extra work for you taking them out and then putting them back. I would much rather just have everything there with a reasonable indication of what the values do so we can set equivalent modes.

**Comment by ACastanza** [comment]
Wrt parameter order, my preference would be to try to keep the order as close to the current version of GSEA as possible, with something like this:

run_gsea(
        sc_el_sa,
        se_el_, 
        la_, 
        pe="label", 
        n_pe=1000,
        fu=options.rme,
        mi=5, 
        ma=500,
        al=options.eme, 
        we=1.0, 
        no=None, 
        se=1729,
        n_pl=25, 
        ad=None,
        pa="gsea_results", 
	)

**Comment by KwatME** [comment]
https://github.com/KwatME/gsea/issues/10

https://github.com/KwatME/gsea/issues/9
